# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"torch2np": "data.ipynb",
         "denorm": "data.ipynb",
         "ImgFolderPipeline": "data.ipynb",
         "TFRecordPipeline": "data.ipynb",
         "SubsetSampler": "data.ipynb",
         "SubsetDataloader": "data.ipynb",
         "ImgCSVDataset": "data.ipynb",
         "DaliDataloader": "data.ipynb",
         "leaf_modules": "models.ipynb",
         "gram_matrix": "models.ipynb",
         "get_in_channels": "models.ipynb",
         "get_out_channels": "models.ipynb",
         "reflection_conv": "models.ipynb",
         "conv_layer": "models.ipynb",
         "up_conv_layer": "models.ipynb",
         "get_encoder": "models.ipynb",
         "FeatureLoss": "models.ipynb",
         "AutoEncoder": "models.ipynb"}

modules = ["data.py",
           "models.py"]

doc_url = "https://justinblaber.github.io/style_transfer/"

git_url = "https://github.com/justinblaber/style_transfer/tree/master/"

def custom_doc_links(name): return None
